apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app.kubernetes.io/name: zookeeper
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app.kubernetes.io/name: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zk-cs
  labels:
    app.kubernetes.io/name: zookeeper
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app.kubernetes.io/name: zookeeper
