apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-sentinel
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-setinel
    spec:
      containers:
      - name: sentinel
        image: local-redis:v1
        env:
          - name: SENTINEL
            value: "true"
        ports:
          - containerPort: 26379
            name: sentinel