apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: codis-proxy
  name: redis-sentinel
spec:
  ports:
    - port: 26379
      targetPort: 26379
      name: sentinel
  selector:
    app.kubernetes.io/name: codis-proxy