apiVersion: v1
kind: ReplicationController
metadata:
  name: codis-fe
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: codis-fe
    spec:
      # imagePullSecrets:
      # - name: your-registry
      containers:
      - name: codis-fe
        image: codis-image:local
        imagePullPolicy: Never
        command: ["codis-fe"]
        args: ["--zookeeper","$(ZK_ADDR)","--listen=:8080","--assets=$(CODIS_PATH)/bin/assets"]
        env:
        - name: CODIS_PATH
          value: "/gopath/src/github.com/CodisLabs/codis"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ZK_ADDR
          value: "zookeeper:2181"
        ports:
        - containerPort: 8080
          name: fe
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "0.1"
            memory: 0.1Gi
